name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run formatting check
      run: npm run format:check

    - name: Run type checking
      run: npm run type-check

    - name: Build
      run: npm run build

    - name: Verify build files
      run: |
        if [ ! -f "main.js" ]; then
          echo "main.js not found"
          exit 1
        fi
        if [ ! -f "manifest.json" ]; then
          echo "manifest.json not found"
          exit 1
        fi
        if [ ! -f "styles.css" ]; then
          echo "styles.css not found"
          exit 1
        fi
        echo "All build files present"