name: Maintenance

on:
  schedule:
    - cron: '0 9 * * 0'  # Every Sunday at 9 AM
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated dependencies
        run: |
          echo "Maintenance check started at $(date)" > maintenance-report.txt
          
          # Check for outdated packages
          npm outdated >> maintenance-report.txt 2>&1 || true
          
          # Check for security vulnerabilities
          npm audit >> maintenance-report.txt 2>&1 || true

      - name: Check for deprecated APIs
        run: |
          # Check for deprecated Node.js APIs
          if grep -r "require.*fs" src/; then
            echo "Found fs require - consider using ES modules" >> maintenance-report.txt
          fi
          
          if grep -r "require.*path" src/; then
            echo "Found path require - consider using ES modules" >> maintenance-report.txt
          fi
          
          if grep -r "require.*url" src/; then
            echo "Found url require - consider using ES modules" >> maintenance-report.txt
          fi

      - name: Check for unused dependencies
        run: |
          # This is a basic check - consider using depcheck for more accurate results
          echo "Checking for potentially unused dependencies..." >> maintenance-report.txt
          
          # Check if all imported modules are actually used
          for file in src/*.ts; do
            if [ -f "$file" ]; then
              imports=$(grep "^import" "$file" | wc -l)
              echo "File $file has $imports imports" >> maintenance-report.txt
            fi
          done

      - name: Check for deprecated features
        run: |
          # Check for deprecated JavaScript features
          if grep -r "var " src/; then
            echo "Found var declarations - consider using const/let" >> maintenance-report.txt
          fi
          
          if grep -r "function.*function" src/; then
            echo "Found function declarations - consider using arrow functions" >> maintenance-report.txt
          fi
          
          if grep -r "new Array" src/; then
            echo "Found new Array() - consider using array literals" >> maintenance-report.txt
          fi

      - name: Upload maintenance report
        uses: actions/upload-artifact@v4
        with:
          name: maintenance-report
          path: maintenance-report.txt
          retention-days: 7